### ISSUE TITLE
牛逼！

### ISSUE THREAD

**Issue by MaZhaoYong** [luohongk/SuperVINS#2]
大哥，研究生还没开学就发了SuperVins啊，这让我们这些玩了一年的人感到焦绿

**Comment by luohongk** [comment]
当然是本科有人带我啊

**Comment by wangxingai14106** [comment]
你好，请问可以出一个自带摄像头的实时supervins项目吗？？？？不需要固定数据集的

**Comment by 2805651606** [comment]
> 当然是本科有人带我啊

大佬，什么时候开源呢
